server:
  port: 9090
  servlet:
    context-path: /resource-server
spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9595/auth-server